services:
  - type: web
    name: kashliwal-tgp-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://kashliwal-tgp-api.onrender.com
